### ISSUE TITLE
How to pass Avatar,loaction etc.. attributes

### ISSUE THREAD

**Issue by anandraj204** [tarr11/IntercomDotnet#19]
Need to pass these attribute.

"avatar": {
    "type": "avatar",
    "image_url": "http://example.org/128Wash.jpg"
  },

how to pass via on these code 

 var newuser = client.Users.Post(new { email = "test@test.com" });

**Comment by mgoodfellow** [comment]
The input to the Post function is simply an object, so you can use a `dynamic` to achieve this.

Have you tried:

``` csharp
client.Users.Post(new {
    user_id = 123,
    email = "bob@a.com",
    avatar = new {
        type = "avatar",
        image_url = "http://example.org/128Wash.jpg"
    });
```

**Comment by mgoodfellow** [comment]
Hold on, read the [docs](https://developers.intercom.io/docs/user-model)...

"The user avatar is read only and can not be updated via the API."

**Comment by anandraj204** [comment]
Thanks @mgoodfellow
