### ISSUE TITLE
Issue with Upgrading Intercom_dotnet version 1.0.0.0 to intercomDotNet version 2.0.4.0 

### ISSUE THREAD

**Issue by mahesh0919** [tarr11/IntercomDotnet#23]
Hi I am using previous version of intercom-dotnet (1.0.0.0) in my application to read messages sent from intercom to a user.now I am upgrading your library.

could you please le me know is there any API which provides reading messages sent from intercom to a user. or what is the equivalent API for the below code. code taken from previous version of intercom-dotnet.dll
This will read messages sent to user from intercom.

public dynamic Get(int? user_id = null, string email = null, int? thread_id = null, string current_url = null)
{
return base.Client.Execute("users/message_threads", 0, delegate(RestRequest request)
{
if (thread_id.HasValue)
{
request.AddParameter("thread_id", thread_id);
}
if (email != null)
{
request.AddParameter("email", email);
}
if (user_id.HasValue)
{
request.AddParameter("user_id", user_id.Value);
}
if (current_url != null)
{
request.AddParameter("current_url", current_url);
}
});
}

**Comment by mgoodfellow** [comment]
Hi @mahesh0919,

The old intercom-dotnet library supported the API v1 of Intercom, whereas the v2 of the library targets the new Intercom API v2.

The old `messages` and `message_threads` which used to be bound to users, now look to me to be the new `/conversations` endpoints - see the docs [here](https://developers.intercom.io/reference#user-or-contact-initiated-conversation).

I personally don't have time to write the wrappers for these endpoints as I'm not currently using these features, but it would be great if you want to write them and then submit a PR to incorporate it into the library!

Kind regards,

Mike

**Comment by mahesh0919** [comment]
Hi Mike,

I am currently working on this and will update you once I had done this
feature.

Thanks
Mahesh

**Comment by mgoodfellow** [comment]
Awesome, let me know if you have any questions and I will do my best to try and help!

Kind regards,
Mike

**Comment by mgoodfellow** [comment]
Relates to https://github.com/tarr11/IntercomDotnet/issues/21 (which I missed), so closing https://github.com/tarr11/IntercomDotnet/issues/21 because it can be discussed here

**Comment by mgoodfellow** [comment]
See also #4 to track API v2 support progress

**Comment by mgoodfellow** [comment]
[Package on Nuget](https://www.nuget.org/packages/intercom-dotnet) has been published, new version will be indexed soon
