### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by JustMaier** [tarr11/IntercomDotnet#5]
Can you please update the nuget package?

**Comment by mgoodfellow** [comment]
Hi, I have been on holiday for the last week so haven't had a chance. I will push a new version of the package (2.0.0.0) with support of the currently supported endpoints on the Intercom V2 API. Hope to get this done tomorrow.

See https://github.com/tarr11/IntercomDotnet/issues/4 for the current v2 API support.

**Comment by JustMaier** [comment]
Thanks @mgoodfellow. Looking forward to it.

**Comment by mgoodfellow** [comment]
Hi @JustMaier,

I have pushed the updated package to the nuget gallery.

https://www.nuget.org/packages/intercom-dotnet/

Any issues, let me know via a new issue.

**Comment by JustMaier** [comment]
Thanks
